version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Update NPM
          command: sudo npm install -g npm@latest
      - run:
          name: Install Hexo CLI
          command: |
            sudo npm install hexo-cli -g
      - restore_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM packages
          command: npm ci
      - save_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate blog
          command: hexo generate
      - persist_to_workspace:
          root: public
          paths:
            - "*"
  deploy:
    docker:
      - image: circleci/node:lts-stretch
    steps:
      - checkout
      - run:
          name: Install Hexo CLI
          command: |
            sudo npm install hexo-cli -g
      - restore_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
      - attach_workspace:
          at: public
      - add_ssh_keys:
          fingerprints:
            - "49:bc:d4:67:ae:cb:e7:ee:e0:1c:3e:2d:b3:ed:a7:c6"
      - deploy:
          name: Deploy website
          command: |
            git config --global user.name "Circle CI"
            git config --global user.email "bot@circleci.com"
            cp orchestration/deploy.sh deploy.sh && chmod 755 deploy.sh && sh deploy.sh
  verify:
    docker:
      - image: circleci/node:lts-stretch
    steps:
      - run:
          name: Install BLC
          command: sudo npm install -g broken-link-checker
      - run:
          name: Check broken internal links
          command: blc https://www.iss.am -roe

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
                - gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: dev
      - verify:
          requires:
            - deploy