nav:
  Home: /
  About: /about/me.html
  Writing: /archives/
  Projects: https://github.com/killix

projects_url: https://github.com/killix

customize:
    gravatar:
        email: b@iss.am
    logo:
        enabled: false
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/killix
        linkedin: https://www.linkedin.com/in/issamhakimi
    show_all_posts: false
    post_count: 10
    highlight: pojoaque

# RSS
rss: false

# Plugins
plugins:
#     disqus_shortname: # Disqus Comments Shortname
#     google_analytics: UA-37473492-6 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
  open_graph: # see http://ogp.me
      fb_app_id:
      fb_admins:
      twitter_id:
      google_plus:
